package de.ole101.lodestone.text

import net.kyori.adventure.text.format.TextColor

public object Colors {

    private val colors: MutableMap<String, TextColor> = LinkedHashMap()

    public val ALICE_BLUE: TextColor = register("aliceblue", 0xF0F8FF)
    public val ANTIQUE_WHITE: TextColor = register("antiquewhite", 0xFAEBD7)
    public val AQUA: TextColor = register("aqua", 0x00FFFF)
    public val AQUAMARINE: TextColor = register("aquamarine", 0x7FFFD4)
    public val AZURE: TextColor = register("azure", 0xF0FFFF)
    public val BEIGE: TextColor = register("beige", 0xF5F5DC)
    public val BISQUE: TextColor = register("bisque", 0xFFE4C4)
    public val BLACK: TextColor = register("black", 0x000000)
    public val BLANCHED_ALMOND: TextColor = register("blanchedalmond", 0xFFEBCD)
    public val BLUE: TextColor = register("blue", 0x0000FF)
    public val BLUE_VIOLET: TextColor = register("blueviolet", 0x8A2BE2)
    public val BROWN: TextColor = register("brown", 0xA52A2A)
    public val BURLY_WOOD: TextColor = register("burlywood", 0xDEB887)
    public val CADET_BLUE: TextColor = register("cadetblue", 0x5F9EA0)
    public val CHARTREUSE: TextColor = register("chartreuse", 0x7FFF00)
    public val CHOCOLATE: TextColor = register("chocolate", 0xD2691E)
    public val CORAL: TextColor = register("coral", 0xFF7F50)
    public val CORNFLOWER_BLUE: TextColor = register("cornflowerblue", 0x6495ED)
    public val CORNSILK: TextColor = register("cornsilk", 0xFFF8DC)
    public val CRIMSON: TextColor = register("crimson", 0xDC143C)
    public val CYAN: TextColor = register("cyan", 0x00FFFF)
    public val DARK_BLUE: TextColor = register("darkblue", 0x00008B)
    public val DARK_CYAN: TextColor = register("darkcyan", 0x008B8B)
    public val DARK_GOLDENROD: TextColor = register("darkgoldenrod", 0xB8860B)
    public val DARK_GRAY: TextColor = register("darkgray", 0xA9A9A9)
    public val DARK_GREY: TextColor = register("darkgrey", 0xA9A9A9)
    public val DARK_GREEN: TextColor = register("darkgreen", 0x006400)
    public val DARK_KHAKI: TextColor = register("darkkhaki", 0xBDB76B)
    public val DARK_MAGENTA: TextColor = register("darkmagenta", 0x8B008B)
    public val DARK_OLIVE_GREEN: TextColor = register("darkolivegreen", 0x556B2F)
    public val DARK_ORANGE: TextColor = register("darkorange", 0xFF8C00)
    public val DARK_ORCHID: TextColor = register("darkorchid", 0x9932CC)
    public val DARK_RED: TextColor = register("darkred", 0x8B0000)
    public val DARK_SALMON: TextColor = register("darksalmon", 0xE9967A)
    public val DARK_SEA_GREEN: TextColor = register("darkseagreen", 0x8FBC8F)
    public val DARK_SLATE_BLUE: TextColor = register("darkslateblue", 0x483D8B)
    public val DARK_SLATE_GRAY: TextColor = register("darkslategray", 0x2F4F4F)
    public val DARK_SLATE_GREY: TextColor = register("darkslategrey", 0x2F4F4F)
    public val DARK_TURQUOISE: TextColor = register("darkturquoise", 0x00CED1)
    public val DARK_VIOLET: TextColor = register("darkviolet", 0x9400D3)
    public val DEEP_PINK: TextColor = register("deeppink", 0xFF1493)
    public val DEEP_SKY_BLUE: TextColor = register("deepskyblue", 0x00BFFF)
    public val DIM_GRAY: TextColor = register("dimgray", 0x696969)
    public val DIM_GREY: TextColor = register("dimgrey", 0x696969)
    public val DODGER_BLUE: TextColor = register("dodgerblue", 0x1E90FF)
    public val FIRE_BRICK: TextColor = register("firebrick", 0xB22222)
    public val FLORAL_WHITE: TextColor = register("floralwhite", 0xFFFAF0)
    public val FOREST_GREEN: TextColor = register("forestgreen", 0x228B22)
    public val FUCHSIA: TextColor = register("fuchsia", 0xFF00FF)
    public val GAINSBORO: TextColor = register("gainsboro", 0xDCDCDC)
    public val GHOST_WHITE: TextColor = register("ghostwhite", 0xF8F8FF)
    public val GOLD: TextColor = register("gold", 0xFFD700)
    public val GOLDENROD: TextColor = register("goldenrod", 0xDAA520)
    public val GRAY: TextColor = register("gray", 0x808080)
    public val GREY: TextColor = register("grey", 0x808080)
    public val GREEN: TextColor = register("green", 0x008000)
    public val GREEN_YELLOW: TextColor = register("greenyellow", 0xADFF2F)
    public val HONEY_DEW: TextColor = register("honeydew", 0xF0FFF0)
    public val HOT_PINK: TextColor = register("hotpink", 0xFF69B4)
    public val INDIAN_RED: TextColor = register("indianred", 0xCD5C5C)
    public val INDIGO: TextColor = register("indigo", 0x4B0082)
    public val IVORY: TextColor = register("ivory", 0xFFFFF0)
    public val KHAKI: TextColor = register("khaki", 0xF0E68C)
    public val LAVENDER: TextColor = register("lavender", 0xE6E6FA)
    public val LAVENDER_BLUSH: TextColor = register("lavenderblush", 0xFFF0F5)
    public val LAWN_GREEN: TextColor = register("lawngreen", 0x7CFC00)
    public val LEMON_CHIFFON: TextColor = register("lemonchiffon", 0xFFFACD)
    public val LIGHT_BLUE: TextColor = register("lightblue", 0xADD8E6)
    public val LIGHT_CORAL: TextColor = register("lightcoral", 0xF08080)
    public val LIGHT_CYAN: TextColor = register("lightcyan", 0xE0FFFF)
    public val LIGHT_GOLDENROD_YELLOW: TextColor = register("lightgoldenrodyellow", 0xFAFAD2)
    public val LIGHT_GRAY: TextColor = register("lightgray", 0xD3D3D3)
    public val LIGHT_GREY: TextColor = register("lightgrey", 0xD3D3D3)
    public val LIGHT_GREEN: TextColor = register("lightgreen", 0x90EE90)
    public val LIGHT_PINK: TextColor = register("lightpink", 0xFFB6C1)
    public val LIGHT_SALMON: TextColor = register("lightsalmon", 0xFFA07A)
    public val LIGHT_SEA_GREEN: TextColor = register("lightseagreen", 0x20B2AA)
    public val LIGHT_SKY_BLUE: TextColor = register("lightskyblue", 0x87CEFA)
    public val LIGHT_SLATE_GRAY: TextColor = register("lightslategray", 0x778899)
    public val LIGHT_SLATE_GREY: TextColor = register("lightslategrey", 0x778899)
    public val LIGHT_STEEL_BLUE: TextColor = register("lightsteelblue", 0xB0C4DE)
    public val LIGHT_YELLOW: TextColor = register("lightyellow", 0xFFFFE0)
    public val LIME: TextColor = register("lime", 0x00FF00)
    public val LIME_GREEN: TextColor = register("limegreen", 0x32CD32)
    public val LINEN: TextColor = register("linen", 0xFAF0E6)
    public val MAGENTA: TextColor = register("magenta", 0xFF00FF)
    public val MAROON: TextColor = register("maroon", 0x800000)
    public val MEDIUM_AQUAMARINE: TextColor = register("mediumaquamarine", 0x66CDAA)
    public val MEDIUM_BLUE: TextColor = register("mediumblue", 0x0000CD)
    public val MEDIUM_ORCHID: TextColor = register("mediumorchid", 0xBA55D3)
    public val MEDIUM_PURPLE: TextColor = register("mediumpurple", 0x9370DB)
    public val MEDIUM_SEA_GREEN: TextColor = register("mediumseagreen", 0x3CB371)
    public val MEDIUM_SLATE_BLUE: TextColor = register("mediumslateblue", 0x7B68EE)
    public val MEDIUM_SPRING_GREEN: TextColor = register("mediumspringgreen", 0x00FA9A)
    public val MEDIUM_TURQUOISE: TextColor = register("mediumturquoise", 0x48D1CC)
    public val MEDIUM_VIOLET_RED: TextColor = register("mediumvioletred", 0xC71585)
    public val MIDNIGHT_BLUE: TextColor = register("midnightblue", 0x191970)
    public val MINT_CREAM: TextColor = register("mintcream", 0xF5FFFA)
    public val MISTY_ROSE: TextColor = register("mistyrose", 0xFFE4E1)
    public val MOCCASIN: TextColor = register("moccasin", 0xFFE4B5)
    public val NAVAJO_WHITE: TextColor = register("navajowhite", 0xFFDEAD)
    public val NAVY: TextColor = register("navy", 0x000080)
    public val OLD_LACE: TextColor = register("oldlace", 0xFDF5E6)
    public val OLIVE: TextColor = register("olive", 0x808000)
    public val OLIVE_DRAB: TextColor = register("olivedrab", 0x6B8E23)
    public val ORANGE: TextColor = register("orange", 0xFFA500)
    public val ORANGE_RED: TextColor = register("orangered", 0xFF4500)
    public val ORCHID: TextColor = register("orchid", 0xDA70D6)
    public val PALE_GOLDENROD: TextColor = register("palegoldenrod", 0xEEE8AA)
    public val PALE_GREEN: TextColor = register("palegreen", 0x98FB98)
    public val PALE_TURQUOISE: TextColor = register("paleturquoise", 0xAFEEEE)
    public val PALE_VIOLET_RED: TextColor = register("palevioletred", 0xDB7093)
    public val PAPAYA_WHIP: TextColor = register("papayawhip", 0xFFEFD5)
    public val PEACH_PUFF: TextColor = register("peachpuff", 0xFFDAB9)
    public val PERU: TextColor = register("peru", 0xCD853F)
    public val PINK: TextColor = register("pink", 0xFFC0CB)
    public val PLUM: TextColor = register("plum", 0xDDA0DD)
    public val POWDER_BLUE: TextColor = register("powderblue", 0xB0E0E6)
    public val PURPLE: TextColor = register("purple", 0x800080)
    public val REBECCA_PURPLE: TextColor = register("rebeccapurple", 0x663399)
    public val RED: TextColor = register("red", 0xFF0000)
    public val ROSY_BROWN: TextColor = register("rosybrown", 0xBC8F8F)
    public val ROYAL_BLUE: TextColor = register("royalblue", 0x4169E1)
    public val SADDLE_BROWN: TextColor = register("saddlebrown", 0x8B4513)
    public val SALMON: TextColor = register("salmon", 0xFA8072)
    public val SANDY_BROWN: TextColor = register("sandybrown", 0xF4A460)
    public val SEA_GREEN: TextColor = register("seagreen", 0x2E8B57)
    public val SEA_SHELL: TextColor = register("seashell", 0xFFF5EE)
    public val SIENNA: TextColor = register("sienna", 0xA0522D)
    public val SILVER: TextColor = register("silver", 0xC0C0C0)
    public val SKY_BLUE: TextColor = register("skyblue", 0x87CEEB)
    public val SLATE_BLUE: TextColor = register("slateblue", 0x6A5ACD)
    public val SLATE_GRAY: TextColor = register("slategray", 0x708090)
    public val SLATE_GREY: TextColor = register("slategrey", 0x708090)
    public val SNOW: TextColor = register("snow", 0xFFFAFA)
    public val SPRING_GREEN: TextColor = register("springgreen", 0x00FF7F)
    public val STEEL_BLUE: TextColor = register("steelblue", 0x4682B4)
    public val TAN: TextColor = register("tan", 0xD2B48C)
    public val TEAL: TextColor = register("teal", 0x008080)
    public val THISTLE: TextColor = register("thistle", 0xD8BFD8)
    public val TOMATO: TextColor = register("tomato", 0xFF6347)
    public val TURQUOISE: TextColor = register("turquoise", 0x40E0D0)
    public val VIOLET: TextColor = register("violet", 0xEE82EE)
    public val WHEAT: TextColor = register("wheat", 0xF5DEB3)
    public val WHITE: TextColor = register("white", 0xFFFFFF)
    public val WHITE_SMOKE: TextColor = register("whitesmoke", 0xF5F5F5)
    public val YELLOW: TextColor = register("yellow", 0xFFFF00)
    public val YELLOW_GREEN: TextColor = register("yellowgreen", 0x9ACD32)

    public val byName: Map<String, TextColor> = this.colors.toMap()

    public val values: List<TextColor> = this.colors.values.toList()

    public val names: Set<String> = this.colors.keys.toSet()

    public fun named(name: String): TextColor? {
        return this.colors[name.filter { it.isLetter() }.lowercase()]
    }

    private fun register(name: String, value: Int): TextColor {
        return TextColor.color(value).also { this.colors[name] = it }
    }
}
