[versions]
kotlin-jvm = "2.4.20"

minestom = "2026.09.12-26.2"
adventure-text-minimessage = "5.2.0"

kotest = "6.2.5"

[libraries]
minestom = { module = "net.minestom:minestom", version.ref = "minestom" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-text-minimessage" }

kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
